services:

  order-service:
    build: ./OrderService
    container_name: order-service
    ports:
      - "5000:5000"


  customer-service:
    build: ./CustomerService
    container_name: customer-service
    ports:
      - "5002:5002"


  restaurant-service:
    build: ./RestaurantService
    container_name: restaurant-service
    ports:
      - "5004:5004"


  delivery-service:
    build: ./DeliveryService
    container_name: delivery-service
    ports:
      - "5004:5004"    


  admin-notification-service:
    build:
      context: ./AdminNotificationService
    ports:
      - "7000:7000"
    volumes:
      - ./AdminNotificationService:/app 


  auth-service:
    build:
      context: ./AuthService
    ports:
      - "7001:7001"
    volumes:
      - ./AuthService:/app
    depends_on:
      - admin-notification-service


  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - order-service
      - customer-service
      - restaurant-service
