apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-notification-service
  template:
    metadata:
      labels:
        app: admin-notification-service
    spec:
      containers:
      - name: admin-notification-service
        image: localhost/systemadminone-admin-notification-service:latest  # replace
        imagePullPolicy: Never
        ports:
        - containerPort: 7002
---
apiVersion: v1
kind: Service
metadata:
  name: admin-notification-service
spec:
  selector:
    app: admin-notification-service
  ports:
  - port: 7002
    targetPort: 7002
